"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.galleryRoutes = void 0;
const express_1 = require("express");
const gallery_controller_1 = require("../controllers/gallery_controller");
const galleryRoutes = (0, express_1.Router)();
exports.galleryRoutes = galleryRoutes;
galleryRoutes.post('/gallery', gallery_controller_1.createGallery);
galleryRoutes.get('/gallery', gallery_controller_1.getGallery);
galleryRoutes.get('/gallery/:id', gallery_controller_1.getGalleryById);
galleryRoutes.put('/gallery', gallery_controller_1.updateGallery);
galleryRoutes.delete('/gallery', gallery_controller_1.deleteGallery);
